version: '3.9'                                                                                                          
                                                                                                                        
services:                                                                                                               
  db:                                                                                                         
    image: mysql:latest                                                                                                 
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_spanish_ci                                       
    ports:                                                                                                              
      - 3306:3306                                                                                                       
    restart: always                                                                                                     
    environment:                                                                                                        
      - MYSQL_ROOT_PASSWORD=Contrasena
      - MYSQL_DATABASE=peliculaspoo
    volumes:
      - db_mysql_data:/var/lib/mysql
      - ./sql/dump.sql:/docker-entrypoint-initdb.d/dump.sql

  db_phpMyAdmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=Contrasena
    depends_on:
      - db
volumes:
  db_mysql_data:

